### ISSUE TITLE
Explore updating the complete tutorial to newer versions of Astro (and other dependencies)

### ISSUE THREAD

**Issue by TheOtterlord** [withastro/blog-tutorial-demo#10]
This tutorial is outdated, and currently using v1 of Astro. Explore whether this can be updated to v2 (or the upcoming v3), or if it's best to keep this on v1 as it works for the scope of the content in the tutorial.

**Comment by roebi** [comment]
just finished this blog-tutorial.
current running on 'my' blog-tutorial netfly.app
https://stately-seahorse-ef56b6.netlify.app
included with the rss feed:
https://stately-seahorse-ef56b6.netlify.app/rss.xml
PS: i am not sure how long i let run this app, today is 20230806.
because an alternative can be to switch to 'run' it in github pages.

my dependencies are:

  "dependencies": {
    "@astrojs/preact": "^2.2.1",
    "@astrojs/rss": "^2.4.3",
    "astro": "^2.10.1",
    "preact": "^10.16.0"
  }

Greetings Röbi

**Comment by ElianCodes** [comment]
Just updated everything to Astro 3 and peer-dependencies!
