### ISSUE TITLE
Does the RSS feed code still work?

### ISSUE THREAD

**Issue by sarah11918** [withastro/blog-tutorial-demo#12]
It's been a while, and we received a comment.

Would love for someone to revisit the RSS code and verify that it's up to date!

**Comment by roebi** [comment]
just finished this blog-tutorial.

to be precise: i worked with the minimal start and work with
all the codes in the tutorial - not in this repository.

With this
the RSS Feed was generated on 'my' blog-tutorial netfly.app
https://stately-seahorse-ef56b6.netlify.app/rss.xml
PS: i am not sure how long i let run this app, today is 20230806.
because an alternative can be to switch to 'run' it in github pages.

as an addition i made the change in:
addon: https://docs.astro.build/en/guides/content-collections/#migrating-from-file-based-routing
and add a 5th Blog Entry,
with this the RRS Feed works too

more details see
https://github.com/roebi/astro-first-blog

Greetings Röbi

**Comment by sarah11918** [comment]
Thanks, @roebi for letting us know! This is very helpful!

Congrats on the blog, and finishing the tutorial!  :raised_hands:

**Comment by sarah11918** [comment]
Seems to still be OK! Closing for now!

**Comment by roebi** [comment]
a note when using the **base** value:
the **base** value should also be added to the rss feed so that the links to the blog articles are correct.
Example : add **base** value **/roebi-halter-in-blog**
in src/pages/rss.xml.js
Commit such a change as an example:
https://github.com/roebi/roebi-halter-in-blog/commit/9bb6dfb5c67ff0da6bbac9ceae925646fb5e21c9
from line
link: `/blog/${post.slug}/`,
to line
link: `/roebi-halter-in-blog/blog/${post.slug}/`,
**Result rss.xml**
https://roebi.github.io/roebi-halter-in-blog/rss.xml

docs are here:
https://docs.astro.build/en/reference/configuration-reference/#base
here the concrete value '/docs' is added
and a example with ${import.meta.env.BASE_URL} is described

and here:
https://docs.astro.build/en/guides/deploy/github/#how-to-deploy
-> first CAUTION block:
- here the concrete value '/my-repo' is added

ob both docs:
- **please add a hint about the rss links**

**Comment by sarah11918** [comment]
Thanks, @roebi ! I'll open this back up so that someone can work on your suggestions!

**Comment by ElianCodes** [comment]
Hey there! We just updated the blog tutorial to Astro 3 and updated the RSS with it as well!
Thanks for opening an issue and reminding us!
