### ISSUE TITLE
H1 Style in about.astro should be removed in branches unit-5/start, unit-6/start, complete

### ISSUE THREAD

**Issue by pellison512** [withastro/blog-tutorial-demo#28]
Hi, I'm not sure if this is the correct place to raise the issue so please let me know if there's somewhere better.

I'm a new Astro developer following along with your [tutorial](https://docs.astro.build/en/tutorial/4-layouts/1/) when I got to section 4 and came across the "Try it yourself" language:

> Delete anything from each page that that page is no longer responsible for rendering, because it is being handled by the layout, including:

>    HTML elements
>    Components and their imports
>   CSS rules in a <style> tag (e.g. <h1> in your About page)
>   <script> tags

The `<h1>` CSS rule is still present in these branches, and has no effect on the CSS of the site. Therefore, I think it should be removed from branches `unit-5/start`, `unit-6/start`, and `complete`.

I have a branch with this change based off `unit-5/start`, but I'm not sure how to contribute. 

Thanks in advance!

**Comment by sarah11918** [comment]
Hi! This is absolutely the place to report these issues, and sorry that it has taken us until now to get back to you!

We are updating this code for Astro code changes in v5 and taking the opportunity to correct some mistakes and yes, we are fixing that one too! 

We decided to stop maintaining the individual branches in part because, as you said, when we fix one part of the tutorial in docs, that can mean coming back and very carefully (and in a specific order) updating these branches. That makes it difficult to allow the community to help update and maintain this code. We received feedback that the individual unit branches weren't being used very much, and they are a lot of work to maintain since we are regularly updating the docs content. So we decided to only maintain a final version of the code at this point since we don't have the resources to keep up our original idea of different branches, and our plan is to delete them in the next few days.

I will be updating the `completed` and `content-collections` branches for next week's release, and then will be actively monitoring this repo for issues and PRs as people start taking the new tutorial. I know you've already taken the tutorial and are not likely to be going through the files and contributing back, but I hope that we are setting ourselves up for better maintenance in the future so that the next time someone finds something, they can easily contribute back!
