### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by lquenti** [withastro/blog-tutorial-demo#8]
Hey! I'd actually love to use this as an basis for my blog. Unfortunately, if a license was never set, all rights are reserved to you and I am not allowed to use the code formally.

Would it be okay if you license it?

If you just want people to use it without being legally required to disclose this tutorial, CC0 or UNLICENSE would make sense.
Otherwise probably Apache2 oder MIT, GPL is most likely too restrictive for the community!
```[tasklist]
### Tasks
- [x] Decide on a License
- [x] Add the License to the Repo
```

**Comment by sarah11918** [comment]
Hi @lquenti! Thank you for this message, and yes, let's get this figured out!

We typically use the MIT license for Astro public repos. You can see all our templates, which are also available for use, here: https://github.com/withastro/astro/tree/main/examples

I assume since all of these templates exist under the main `withastro/astro` repository, they are all covered by the license in the root of the project and therefore do not show up in each individual starter template.

I will loop @FredKSchott into this conversation, but my assumption is that we can add the same MIT license here to this repository.

**Comment by delucis** [comment]
Thanks @lquenti — just added an MIT license to the repo. Thanks for letting us know it was missing 🙌
